language: generic 
sudo: required
services:
  - docker
# change
before_install:
  - docker build -t sergiomermont/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sergiomermont/docker-react npm run test